### ISSUE TITLE
Retargeting your project causes "C:" drive to appear in project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1021]
Team Procedure that leads to the bug

1. Start new .Net Core console app target 4.5.2 (also tested 4.6.2)
2. Right click on project-->properties and set .NetCoreApp to 1.1 (default is 1.0)
3. Save properties file and close
4. Right click Dependencies Nuget-->Updates and install Microsoft.NETCore.App v1.1

Your C: Drive should appear in Solution explorer down to .nuget-->(folders)-->1.4.0->runtimes-->win-->native (see screenshot in comment below)

![image](https://cloud.githubusercontent.com/assets/1103906/21409930/688aea22-c831-11e6-8438-d6374520e45c.png)

See also:
https://developercommunity.visualstudio.com/content/problem/7620/danger-c-drive-appears-in-solution-explorer-when-u.html
https://github.com/aspnet/Tooling/issues/911

**Comment by srivatsn** [comment]
This is because of an issue in the diasymreader.native package which is a newly added dependency in 1.1. The package has been fixed and https://github.com/dotnet/corefx/issues/14627 is tracking updating the package in 1.1.1 for this issue. 

The package is adding a Content item and so the project system is basically doing showing the content item. Not sure if there's anything we can do to fix the 1.1.0 experience. Any ideas?

**Comment by davkean** [comment]
Yep, but we should figure out if this is the correct behavior for CPS. This is a different behavior from the legacy project system where it wouldn't show items that came from targets. 

I suspect that other packages do this same thing, such as the desktop version of xUnit.

**Comment by srivatsn** [comment]
@lifengl @jviau @adrianvmsft thoughts?

**Comment by lifengl** [comment]
Unfortunately, the CPS project tree is driven by the instance model of the msbuild evaluation results.  We don't know whether an item is coming from a target or not.  It would be a breaking change too.  You also want to put globbing in targets files.

Sent from my phone

On Dec 29, 2016, at 4:59 AM, Srivatsn Narayanan <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://github.com/lifengl> @jviau<https://github.com/jviau> @adrianvmsft<https://github.com/adrianvmsft> thoughts?

-

**Comment by davkean** [comment]
Today's behavior from inheriting from targets sounds okay, especially given we're making use of this for the globs. However, it sounds like from this: https://github.com/dotnet/roslyn-project-system/issues/1047 the item is marked as `<Visible>false</Visible>`. Upgrading my build so can't check this - but we should at least respect this, and if we're not we should fix that.

**Comment by davkean** [comment]
Just tested this, CPS _does_ respect `<Visible>false</Visible>` on an item, however, it's creating folders in the visible that represent the path to those items, even if there are no visible items. 

That, I think is the bug.

**Comment by lifengl** [comment]
I agree it is somewhat a bug.

It would be tricky to fix though.  Because it only happens when you have some target files like this, maybe we can move it after RTM.

Currently, the visibility and other flags are calculated by tree property providers, but only parent node affects children.  No visible children is a condition not supported by this model or we will produce loop dependencies and cannot control the calculation order.

The tree provider has a very complicated logic and messy code already, so fixing this would be risky.  Because this specific problem is fixed by fixing the target file, my suggestion is to postpone extra changes in the RTM.

Sent from my phone

On Dec 29, 2016, at 7:45 AM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


Just tested this, CPS does respect <Visible>false</Visible> on an item, however, it's creating folders in the visible that represent the path to those items, even if there are no visible items.

That, I think is the bug.

-

**Comment by dsplaisted** [comment]
@lifengl How do you fix this in the target file?  My understanding of @davkean's description is that even if you set Visible to false on the item, the folder structure still shows up.

**Comment by lifengl** [comment]
I see.  I thought those items would be removed from the target file, or using some item types, which would not be shown.

A workaround may be that you add a folder node to the target file, and set the visibility to false.

The default folder rule doesn't support visible, so you have to update the folder rule too.

Sent from my phone

On Dec 29, 2016, at 10:21 AM, Daniel Plaisted <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://github.com/lifengl> How do you fix this in the target file? My understanding of @davkean<https://github.com/davkean>'s description is that even if you set Visible to false on the item, the folder structure still shows up.

-

**Comment by cjbhaines** [comment]
@lifengl I think it would be good to get this fixed before RTM. I reported this already and I've seen many other duplicates. It looks really weird and I think you are going to get a lot of noise if you release this as it is.

**Comment by rrelyea** [comment]
yes, we got at least 2 vsfeedback issues to the nuget team. likely many dupes.

**Comment by lifengl** [comment]
Hmm,

I guess set visible = false will add an show--when-show-all-file-is-on item, so they will be shown when the user turns on the option.  That is not what we want.  We need at least fix the CPS tree flag logic and change it to always-hidden for nodes outside of the project cone.  Only fix the top node should be enough.

I need think about the second part of the fix.  I think we need add one more tree flag show-when-child-visible.  Unfortunately, we may have used all 32 bits flags.  I think we need expand flags to 64 bits, by define a new 64 bits Enum type and a new set of overloads to prevent any breaking change.

This new flag will be set for all inferred folder node and not explicit folder node.  This new flag will allow us to maintain that the tree flag is only affected by the parent chain but not any child node, and easily doable by updating the tree flag calculating logic.

The logic need more change is to calculate visibility based on tree flags.  This part is not extensible by 3rd party like the tree flag calculator, so the fix can be controlled.

Sent from my phone

On Dec 30, 2016, at 6:10 AM, Rob Relyea <notifications@github.com<mailto:notifications@github.com>> wrote:


yes, we got at least 2 vsfeedback issues to the nuget team. likely many dupes.

-

**Comment by srivatsn** [comment]
This has now been fixed in CPS. Verified on latest build.
