### ISSUE TITLE
VS 2017 RC 15.0.26014.0 Continually building with new project system

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn-project-system#1038]
I'm seeing VS 2017 continually compile, eating CPU and battery with the current MiniProfiler solution ([exact commit here](https://github.com/MiniProfiler/dotnet/tree/9f46ce58d730f8899195bcf36bf3bfb1feff2329)). There's a consistent stack of NuGet trying to restore (`NuGet.PackageManagement.VisualStudio.SolutionRestoreWorker`), but that may just be the normal behavior (waiting point) and not related. Or it may be triggering the builds, I'm not sure.

I don't have time to dig for a few days, but I took a few successive dumps of both VS 2017 and MSBuild ready to upload (just give me an endpoint). I have been editing the project files in VSCode as well as VS 2017, but sometimes this happens just when opening the solution and doing *nothing* else. It's not 100% though.

I'm happy to gather whatever information is needed; I'm on VS 2017 RC 15.0.26014.0.

In case it helps immediately (without dumps), here are 2 sets of thread stacks. They're *far* too big for an issue (...did you know GitHub has a 65,536 issue character limit? [I just found out!](https://twitter.com/Nick_Craver/status/813411683737759744)), so a gist it is: https://gist.github.com/NickCraver/262eafb63ce36a0c7c87d96a31535673

**Comment by davkean** [comment]
By continually compile, what do you mean exactly? Is there a visible build going on in Visual Studio? Or just the compiler service going on in the background?

**Comment by NickCraver** [comment]
@davkean no visible activity in Visual Studio - only sign this was happening was CPU being eaten by Parallels, and me looking at Task Manager to find the culprit. Both VS 2017 and MSBuild are eating 10% CPU a piece, so both are in play...but it's a background operation from the user/UI point of view.

**Comment by davkean** [comment]
Okay, we'll investigate the stack. Do you have Live Unit Testing turned on?

**Comment by NickCraver** [comment]
Nope on live unit testing - I couldn't get it to work at the time and disabled it again after tinkering for an hour.

**Comment by mavasani** [comment]
I tried to repro this issue on the latest VS2017 prerel build, but with no luck:
```
Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26028.6 D15PREREL
```

@NickCraver I opened the MiniProfiler.sln, was able to restore and build it, but opening the solution in VS and waiting for background activity doesn't show any MSBuild or devenv CPU consumption, as mentioned in your repro. I also played around with editing csproj files, but any CPU activity after edits last for a few seconds and it goes back to 0% for devenv/MSBuild.

I think we will need a dump OR an ETL trace to identify the culprit here. Can you collect the trace with the following steps?

1. Download PerfView from https://www.microsoft.com/en-us/download/details.aspx?id=28567
2. Start VS and execute your scenario till you see the high CPU usage.
3. In PerfView, click Collect -> Collect -> Start Collection (note the location where the trace is collected)
4. Wait for few seconds for the trace collection
5. Stop Collection in PerfView
6. Share the ETL trace generated by PerfView - Let me know once you have a trace and I can provide you a onedrive link to upload it.

**Comment by NickCraver** [comment]
@mavasani Sorry, I just now got back to this - I have the trace (38MB), do you want to send me an upload location? My email is craver at stackoverflow.

**Comment by mavasani** [comment]
I followed up with @NickCraver offline. I investigated his trace but unfortunately there seems to be nothing suspicious in devenv/MSBuild in the trace. Additionally, there are no NuGet related stacks in it. Nick, can you collect couple more traces and upload it? Thanks again.

**Comment by NickCraver** [comment]
@mavasani absolutely - I'll capture several. I'm seeing this consistently in Task Manager. I'm updated to the latest RC build today...will see if I can repro tonight or this weekend (as soon as the snow allows!)

**Comment by NickCraver** [comment]
@mavasani I was trying to get you additional dumps but I simply cannot get this to happen after the 15.0.26020.0 update. So yay! I'm not sure what the change was, but whatever I was hitting went from very consistent to resolved.

Closing this out to cleanup.
