### ISSUE TITLE
Visual Studio hangs unloading projects

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1089]
@jnm2 wrote:

> @davkean I'll get a repro for the hang when reloading after saving an edit to the `<TargetFrameworks>` > value. In the meantime, you can repro the hang when unloading projects in general by cloning > https://github.com/nunit/nunit and opening `src/nunit.sln`, making sure all projects are loaded (by > building?), and then closing the solution or trying to open a new solution. It gets as far as unloading project 6 of 60 and seems to hang indefinitely.

**Comment by davkean** [comment]
I suspect this is CPS flushing pending async tasks and blocking on the NuGet restore task.

It should be fixed, but we should verify.

**Comment by jnm2** [comment]
I apologize. I'm sure it was some extension setup conflict on my end. After disabling and reenabling NCrunch and ReSharper, the issue has disappeared.
The odd thing is that the same thing has happened on all three machines I use, and there are always MEF errors shown after installing NRunch and ReSharper. I don't know what the real bug is here, if any.

**Comment by srivatsn** [comment]
Closing this since it appears to be related to some extensions. If you are still seeing this please reopen.
