### ISSUE TITLE
Ready Status but MSBuild Doing stuff - dump attached.

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/roslyn-project-system#1222]
Following a migrate, with VS2017RC (15.0.26116.0 D15REL), I right-clicked on a solution in order to perform a full build.  Almost immediately, VS showed ready in the status bar but the build seemingly did not continue.  Here is the dump that @srivatsn created: https://www.dropbox.com/s/2m89jiqudv65x4p/devenv.dmp?dl=1

/cc @srivatsn @morrisjoe

**Comment by davkean** [comment]
First thing I noticed is that WebProjectTreeModifier is incorrectly looking up the results of a property (WebRootFolder) to determine it's state. It's supposed to be [telling the tree about that property](https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/AppDesignerFolderProjectTreePropertiesProvider.cs#L62) via IProjectTreeSettingsProvider so that the tree knows to update when the properties changes. @BillHiebert @abpiskunov

**Comment by davkean** [comment]
Moved to: https://devdiv.visualstudio.com/DevDiv/VS%20IDE/_workitems?id=372930&fullScreen=false&_a=edit
