### ISSUE TITLE
When targeting desktop, you can't add framework references

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1251]
1. File -> New -> Class Library (.NET Standard)
2. Edit ClassLibary1.csproj
3. Change target framework to:

```
  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>
```

4. Right-click project, choose Add -> Reference

Expected: A way to add framework references
Actual: No way to add framework references, nor COM references

![image](https://cloud.githubusercontent.com/assets/1103906/22101213/8f94c8b6-de86-11e6-9102-176a633d4261.png)

**Comment by abpiskunov** [comment]
isn't it related to the issue which explicitly disabled it? Remember i added a comment about how we did it in xproj  there?

**Comment by RaulPerez1** [comment]
See #966, the plan was to tackle that scenario post RTW

**Comment by srivatsn** [comment]
#966 is for multi-targeting projects. This one is a single target. @RaulPerez1 In this case we should not be adding the capability to filter out the page right?

**Comment by davkean** [comment]
Where was that plan decided? I made this comment: https://github.com/dotnet/roslyn-project-system/issues/400#issuecomment-265328709 under the impression that we wouldn't regress projects target desktop.

**Comment by RaulPerez1** [comment]
Just debugged though this and I believe this is exposing a bigger issue. The SDK import happens before the project contents are evaluated so all the checks in the targets which are using values that you're overriding in the project would use the default value (in this particular case TFM = .NetCoreApp). Moving the exact same check from the targets to the project file (after the TFM line) has the right behavior which was what we had before the MsBuild SDK change.

**Comment by srivatsn** [comment]
No, the sdk attribute adds an import to both the top and bottom of the file - so it's not different from before.

I think this is https://github.com/Microsoft/msbuild/issues/1475

MSBuild is ignoring conditions for item removes. So no matter what TFM you have, the ReferenceManagerAssemblies capability is removed since [this condition](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L258) is ignored  

@cdmihai

Btw an easy way to diagnose capabilities is to add 

```
  <ItemGroup>
    <ProjectCapability Include="DiagnoseCapabilities" />
  </ItemGroup>
```

to the project. This renders the capabilities for that project in Solution explorer:

![image](https://cloud.githubusercontent.com/assets/20570/22321761/2aad24c8-e34c-11e6-95af-54c5c1a737c2.png)

**Comment by srivatsn** [comment]
This is now fixed in D15Rel.
