### ISSUE TITLE
Friendly reminder to update Azure VS2017RC VM to current version

### ISSUE THREAD

**Issue by julielerman** [dotnet/roslyn-project-system#1275]
I'm not sure where to drop this note so maybe someoe on the team can "forward" it.
When RC2 was already out, I created a new VS2017 RC VM on the Azure portal, I did not realize I was getting RC1 until I discovered that it was not behaving correctly. Then I had to do an update which was annoying. So perhaps when RC3 is out, someone on this team can reach out to whomever is responsibe for the VMs and not only get it updated but have the description reflect the version. Here's a screenshot of the VM I'm referring to:

![image](https://cloud.githubusercontent.com/assets/5007120/22152567/839895c2-def1-11e6-8b85-0d9cd7e76952.png)

**Comment by PhilLee-MSFT** [comment]
Hi Julie.  Thanks for the feedback.  I own the system images we publish to Azure that VS installed - including VS 2017 RC.  I'm surprised that you got an "RC1" image after "RC2" was published since we're updating the system images within a day or two of public availability.  Can you confirm the VS version (through Help -> About)?  The branding (description, picture, heading) of the images won't change though the version of VS will...

thanks.
Phil

**Comment by julielerman** [comment]
Hi Phil. Sadly, I had created a VERY temporary search service on my azure account (I already had the free one, so this was S1) and forgot to delete it so it ate up my credits and I'm just waiting out the billing cycle. So I can't look at that VM. What I recall is that some features I had been reading about weren't working as expected. So I found John M's blog post about the update (https://blogs.msdn.microsoft.com/visualstudio/2016/12/12/updating-visual-studio-2017-release-candidate/) and updated via the link he provided and then the behavior was correct.
Good to know that you're on it. Thanks! I'm happy to have this issue closed. :)
