### ISSUE TITLE
Attempting to run a class library that's been turned into a console app shows an error about "RunCommand" missing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1309]
1. Attempt to F5 the attached project: [ClassLibrary2.zip](https://github.com/dotnet/roslyn-project-system/files/722659/ClassLibrary2.zip)

Expected: To run
Actual: 

```
---------------------------
Microsoft Visual Studio
---------------------------
Unable to run your project. The "RunCommand" property is not defined.
---------------------------
OK   
---------------------------
```

**Comment by davkean** [comment]
I cannot for the life of me figure out how to run this project. I've deleted the launchsettings.js, I've blown away the build directory.

**Comment by mavasani** [comment]
The issue is with the SDK. There are bunch of places in the [SDK targets](https://github.com/dotnet/sdk/blob/d20405f91a2959fa91fea6285d9a896286727f2a/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L257) where we set `RunCommand` property, but none of them seems to be doing it the target framework identifier is .NetStandard. I'll port this bug to the SDK repo.

**Comment by mavasani** [comment]
Ported to https://github.com/dotnet/sdk/issues/833
