### ISSUE TITLE
TFM->TFMs causes files to show up in Miscellaneous Files

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#1321]
Testing with d15prerel/26120.04, and the NuGet and SDK changes from Matt.

**Steps**:
1. Create a new class library
2. Edit the project file. Change TFM to TFMs, use `net461;netstandard1.4`.
3. Save

**Expected**:
Class files from the project are considered in the project, with a dropdown for selecting what framework:
![image](https://cloud.githubusercontent.com/assets/2371880/22222576/48efb7ac-e16c-11e6-8080-979a005b1159.png)

**Actual**:
Class files from the projects are in the miscellaneous files project:
![image](https://cloud.githubusercontent.com/assets/2371880/22222633/7acca168-e16c-11e6-989d-7ebac1a13185.png)

Unloading and reloading the project causes the TFMs to be correctly detected.

**Comment by 333fred** [comment]
Found during testing Scenario 31.

**Comment by mavasani** [comment]
I don't understand how this is blocking release. User is going from single tf to multi tf, and close and re-open solution resolves the issue, which I believe is a reasonable workaround. Note that this behavior hasn't changed since initial implementation.

**Comment by srivatsn** [comment]
I assume miscellaneous files here means that there's just basic language service right? 100% of users who try cross-targeting for the first time will run into this and while the workaround is simple, this given the impression of immediate brokenness. I've seen a few pieces of vsfeedback related to this issue.

 I didn't realize this has always been the case. Do we know what the issue is?

**Comment by mavasani** [comment]
I think issue is due to fact that TargetFramework based project doesn't have TF as configuration dimension, hence is fundamentally different then TargetFrameworks based one, where we have additional project configuration dimension for TargetFramework.

This wasn't really an issue until the default property in project file was TargetFrameworks, with single entry and users can just add more frameworks to existing property; user was unlikely to ever change the property name themselves. We basically made this move from single TF to multi TF more complicated for users by changing the default property to TargetFramework.

I believe we should keep TargetFrameworks as the default property in project template and make TargetFramework only set by SDK for inner project. This would also prevent weird crashes/error message when user edits TargetFramework and adds additional frameworks but forgets to change the property name.

**Comment by mavasani** [comment]
Basically, fixing this is going to be more risky then making it less likely to occur, and at the same time also improving the user experience for csproj edit to move from single to multi TF and vice versa.

Btw, what was the reason we changed default property from TFs to TF in first place?

**Comment by srivatsn** [comment]
> Btw, what was the reason we changed default property from TFs to TF in first place?
A large number of projects are not going to be multi-targeting projects and so making them go through an outer and inner build is both a perf issue and also a functional one because extending a multi-targeting project's targets is not straightforward. So forcing that on all projects is a problem and I think switching it to TFs will cause more problems that it can solve.

So if TFs is fundamentally different should we treat it as a rude-edit and cause a real reload instead of the silent one that we do? @BillHiebert @davkean?

**Comment by mavasani** [comment]
I agree, given the number of project configuration dimensions are changing, we should force a reload.

**Comment by natidea** [comment]
A forced reload would also help with https://github.com/dotnet/roslyn-project-system/issues/1226
