### ISSUE TITLE
VS2017RC3 - Portable class library in TargetFrameworks errors on build

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn-project-system#1369]
I used the same format that I did in project.sjon:

```
<TargetFrameworks>net45;net40;net35;net20;netstandard1.0;.NETPortable,Version=v4.5,Profile=Profile259</TargetFrameworks>
```

Error:

```
MSB4086	A numeric comparison was attempted on "$(_TargetFrameworkVersionWithoutV)" that evaluates to "" instead of a number, in condition " '$(_TargetFrameworkVersionWithoutV)' >= '3.5' ".
```

**Comment by onovotny** [comment]
You need to use the short TFM and use properties:

https://github.com/onovotny/Zeroconf/blob/dev/Zeroconf/Zeroconf.csproj#L32-L37

For PCL 259, the properties would be:

```
  <PropertyGroup Condition="'$(TargetFramework)' == 'portable-net45+win8+wpa81+wp8'">
    <TargetFrameworkIdentifier>.NETPortable</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <TargetFrameworkProfile>Profile259</TargetFrameworkProfile>
    <NugetTargetMoniker>.NETPortable,Version=v0.0,Profile=Profile259</NugetTargetMoniker>
    <LanguageTargets>$(MSBuildExtensionsPath32)\Microsoft\Portable\$(TargetFrameworkVersion)\Microsoft.Portable.CSharp.targets</LanguageTargets>
  </PropertyGroup>
```

**Comment by onovotny** [comment]
Note that the Version=v0.0 bit is due to a bug and is being tracked here: https://github.com/dotnet/sdk/issues/492

But the above should work for you.

Downside though -- requires Windows to build, not `dotnet build`. You need to run `msbuild /t:restore` then either `msbuild /t:build` or `msbuild /t:pack` to build and/or pack and build the project.

**Comment by JamesNK** [comment]
I have a PCL build working.

Will PCL ever work with dotnet build?

**Comment by srivatsn** [comment]
https://github.com/dotnet/cli/issues/5504 tracks building non-.NET Core projects with the CLI.

Adding these propertygroups to the SDK so that this is supported OOB is tracked by https://github.com/dotnet/sdk/issues/491

**Comment by JamesNK** [comment]
@onovotny How do you figure out where on disk msbuild for VS 15.0 is located? Is there a registry key with that information somewhere? I don't want to bake the path on my local computer into a build script.

**Comment by onovotny** [comment]
There's no real path that I know of, but that's the value used in the new project templates.

Do file -> new portable class library then see what the imports statement is at the bottom.


`<Import Project="$(MSBuildExtensionsPath32)\Microsoft\Portable\$(TargetFrameworkVersion)\Microsoft.Portable.CSharp.targets" />`

It's the location that all of the project templates use, so I have to assume it's safe to use that path elsewhere as well. Otherwise PCL projects won't load/build at all for VS :)

**Comment by onovotny** [comment]
Doh, just re-read your question and totally missed it...need coffee!

https://github.com/Microsoft/vssetup.powershell

That's probably what you want; it'll show you the available instances of VS (and from there you can get the path to MSBuild from the top level folder).

**Comment by jnm2** [comment]
See also https://github.com/Microsoft/msbuild/issues/1377
