### ISSUE TITLE
Add IsImplicitlyDefined property to PackageReference.xaml

### ISSUE THREAD

**Issue by emgarten** [dotnet/roslyn-project-system#1398]
Add ``IsImplicitlyDefined`` property to PackageReference.xaml to allow passing this information to NuGet from the project system.

Example usage:
```xml
<PackageReference Include="NuGet.Versioning" Version="3.5.0">
  <IsImplicitlyDefined>true</IsImplicitlyDefined>
</PackageReference>
```

NuGet issue: https://github.com/NuGet/Home/issues/4044  targeted for RTW
SDK issue: https://github.com/dotnet/sdk/issues/771

**Comment by rrelyea** [comment]
Actually, the SDK issue discussion, has led us to understand that 2 other components are already using IsImplicitlyDefined metadata on PackageReference for this same meaning. NuGet is going to adapt our feature to use that name too.
Please listen for changes to that metadata, and call nominate as it changes, etc...

(will update the original post above).

**Comment by natidea** [comment]
This property is already defined in both [PackageReference.xaml](https://github.com/dotnet/roslyn-project-system/blob/bd7580d70d7427875a3bb366f4358a3496d9ef64/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PackageReference.xaml#L78) and [ResolvedPackageReference.xaml](https://github.com/dotnet/roslyn-project-system/blob/bd7580d70d7427875a3bb366f4358a3496d9ef64/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedPackageReference.xaml#L56). 

The value would be available in the `Properties` bag on each reference item. I confirmed that nominate is called when the property changes, and the SDK node in the dependency tree is updated. (There may be a bug where the NuGet node is not updated properly, but this may be fixed by https://github.com/dotnet/roslyn-project-system/pull/1392)

**Comment by abpiskunov** [comment]
Nuget node should not contain packages that have IsImplicitlyDefined, they showing under SDK node that you are seeing.

**Comment by emgarten** [comment]
Thanks for verifying @natidea, I must be on an older build that didn't have the change yet.
