### ISSUE TITLE
Transitive references do not show all the time in the Dependency node

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1423]
1. File -> New ConsoleApp (ConsoleApp)
2. File -> New Library (A)
3. File -> New Library (B)
4. Add reference from ConsoleApp -> A
5. Add reference from A -> B

**Expected:**
![image](https://cloud.githubusercontent.com/assets/1103906/22506338/06fc5174-e8d4-11e6-878c-f66436592550.png)
**Actual:**
![image](https://cloud.githubusercontent.com/assets/1103906/22506308/d5b592a6-e8d3-11e6-9ab0-790b3d8d6372.png)

To show the nodes, I had to restart VS. Even if I closed/reopened solution it didn't work.

**Comment by davkean** [comment]
Wonder if this related to: https://github.com/dotnet/roslyn-project-system/pull/1392

**Comment by abpiskunov** [comment]
it might be, true. since if you look at the pic B also does not have anything under A project, not only under ConsoleApp A's dependencies are missing. However it might be something else also. I suppose repro steps are the only thing your did? What was the restore status after adding project references? It's is hard to repro in general such things, if you see this (or similar) again , i would really need you to attach a debugger and set break points in http://index/?rightProject=Microsoft.VisualStudio.ProjectSystem.Managed.VS&file=ProjectSystem%5cVS%5cTree%5cDependencies%5cDependenciesSubTreeProviderBase.cs&line=242 (to see if we get any events from CPS) and in http://index/?rightProject=Microsoft.VisualStudio.ProjectSystem.Managed.VS&file=ProjectSystem%5cVS%5cTree%5cDependencies%5cDependenciesGraphProvider.cs&line=209 to see if it is even called for new dependency nodes or updated ones... on my machine i never could see such things , will try again.

**Comment by srivatsn** [comment]
Can you verify if this still repros?

**Comment by abpiskunov** [comment]
I investigated that further and found a potential issue here , testing a fix right now.

**Comment by davkean** [comment]
I repro this consistently with the MVC repo:

1. git clone https://github.com/aspnet/Mvc
2. cd Mvc
3. git checkout nimullen/migration.badvs
4. Open MVC.sln

tag @NTaylorMullen as FYI
