### ISSUE TITLE
Builds are not skipped when up-to-date

### ISSUE THREAD

**Issue by iskiselev** [dotnet/roslyn-project-system#1438]
Looks like VS 2017 RC3 doesn't skip build of project, even if nothing was changed, at least for Microsoft.NET.Sdk - based projects.
I have solution with 13 projects (4 target frameworks for one of them and 2 target frameworks for others).
It takes 2 minutes to build it for each consequence build, even if I don't change anything.

**Comment by davkean** [comment]
There's two issues that we're aware of:

- The first was that the output was always considered out of date: https://github.com/dotnet/roslyn-project-system/issues/825.  This will be fixed in the next public build. You can test this by setting $(UseHostCompilerIfAvailable) to true in each project to see if this speeds up your build.

- The second is that unlike legacy project system, we call MSBuild to do our up-to-date check, that is yet to be done work, and tracked by: https://github.com/dotnet/roslyn-project-system/issues/825.

**Comment by iskiselev** [comment]
@davkean, thank you for information and advice.
With `<UseHostCompilerIfAvailable>true</UseHostCompilerIfAvailable>` same build takes only 21 second. But to achieve this I also had to remove Microsoft.Net.Compilers NuGet package (we used it to be sure, that on all environments we use same compiler version).

**Comment by davkean** [comment]
Why did you need to remove the package? What happened with it?

**Comment by iskiselev** [comment]
Before I removed this package build speed has not changed and I have not seen in detailed output string:
```
Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn
```

**Comment by davkean** [comment]
Is the speed the same before or after you remove the package but without the property set?

**Comment by iskiselev** [comment]
@davkean, yes, property doesn't change anything. Only removing of package was responsible for speed improvement. Setting property doesn't affect on compilation speed.
For reference, I used Microsoft.Net.Compilers/1.3.2,

**Comment by davkean** [comment]
Okay, I suspect your running in the issue that they aren't NGEN'd, combined with the fact that we were calling it every time due to the first issue I called out above.
