### ISSUE TITLE
Cannot rename nested files in Solution Explorer

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/roslyn-project-system#1529]
Create a new ASP.NET Core project using the "Web Application" template then go to the Solution Explorer and expand the node for "appsettings.json" to see the "appsettings.Development.json" file. You can't rename the child node, either via single click after selection, or context menu (the Rename menu item isn't present).

I'm using VS2017 RC.4+26206.0

![image](https://cloud.githubusercontent.com/assets/249088/22814611/e5facab4-ef09-11e6-9e0c-bf2689d3d954.png)

**Comment by abpiskunov** [comment]
This is CPS...

**Comment by srivatsn** [comment]
Tagging @lifengl - do you have a CPS issue tracking this?

**Comment by davkean** [comment]
Yes, I asked @DamianEdwards to file it here so that we have a public issue tracking it.

**Comment by lifengl** [comment]
That is the default behavior of the other project system like c# project system.  I believe this behavior can be overwritten by extensions.  You can add a project tree action provider to enable/disable basic node operations like deleting or renaming...

Sent from my phone

On Feb 12, 2017, at 4:45 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I asked @DamianEdwards<https://github.com/DamianEdwards> to file it here so that we have a public issue tracking it.

**Comment by davkean** [comment]
You mean a IProjectTreeActionHandler? I had a look at the PhysicalProjectTreeActionHandler and this is a bunch of non-trivial amount of code that we cannot reuse due to an upfront check that blocks renaming of these items. I think we'll want an extension point here - or just a behavior that we can switch on.

**Comment by lifengl** [comment]
IProjectTreeActionHandler is following the chain of responsibility pattern, you can register a high priority handler and only overrides some behavior, and delegate the rest to the next handler, which will eventually go to the default implementation.  Your handler should inherit from ProjectTreeActionHandlerBase, and overrides necessary functions.  I guess you just need implements CanRenameAsync, and only handle the child file case.  That function is explicitly disabled to match the behavior of the other project systems.  If you  enable it, the default implementation can handle renaming correctly (most likely).  

Of course, if someone renames a generated file, a new file with the old name will be produced when the code generator runs again, without deleting the renamed file.  You will have to live with that, I guess...

**Comment by davkean** [comment]
@lifengl The PhysicalProjectTreeActionHandler blocks renaming of child files in it's RenameAsync as well as CanRenameAsync, we should would either need to change that or copy the logic in RenameAsync - which is a non-trivial amount of code. For that last case, you could just block it if it's a generated file.

**Comment by lifengl** [comment]
Yeah, you are right.  I thought we enabled it for project-K, but maybe it was a wrong impression.  We should get rid of the problem in the RenameAsync.  Please open a bug on this, and we can address in the update.

**Comment by davkean** [comment]
This has been completed: https://mseng.visualstudio.com/VSIDEProj/_git/VSIDEProj.CPS/pullrequest/189585?_a=files&path=%2Fsrc

**Comment by stijnherreman** [comment]
@davkean I'm on 15.7.1 and I'm not able to rename a nested file like `appsettings.Development.json`.
