### ISSUE TITLE
SkipCompilerExecution Error

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#1554]
Reported through VS Feedback: https://developercommunity.visualstudio.com/content/problem/17988/rc4-skipcompilerexecution-error.html

After upgrading, my project that used to build fine is now getting this 

```
Severity Code Description Project File Line Suppression State
Error SkipCompilerExecution and ProvideCommandLineArgs should be set before calling the CompileDesignTime target Microsoft.Avro.Core C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\Managed\Microsoft.Managed.DesignTime.targets 243 
```

**Comment by davkean** [comment]
This was filed by @Petermarcu, so far only internal reports of it so far. Will looking at this first thing tomorrow.

**Comment by davidfowl** [comment]
I'll try to get the dump to an internal share tomorrow

**Comment by mavasani** [comment]
This reproes consistently with MVC solution.

**Comment by davkean** [comment]
@mavasani What branch or commit are you sync-d to? I cannot repro this.

**Comment by mavasani** [comment]
1.  git clone https://github.com/aspnet/Mvc.git
2.  git checkout d3cce192925ff41d0d79aba3728ab1ff80962a49
3.  build.cmd from VS admin command prompt
4.  Open MVC.sln at the root of the repo in VS

**Comment by davkean** [comment]
Okay, I have a repro, investigating...

**Comment by davkean** [comment]
No I lost the repro, now I'm just running into https://github.com/dotnet/roslyn-project-system/issues/1575 which is blocking even getting to the compiler.

**Comment by davkean** [comment]
The more I think about this, the more I think this is node reuse.

@Petermarcu @davidfowl @NTaylorMullen @mavasani Did you get above error after building from command-line?

**Comment by mavasani** [comment]
I always executed build.cmd from command line before opening the solution in VS, and the error reproed quite consistently - though it takes quite some time to show up.

**Comment by davkean** [comment]
I can repro this if I run build.cmd while VS is open - looking at logs now, but they don't log global properties :(

**Comment by Petermarcu** [comment]
That sounds possible based on what I recall. I was working on the command line a lot and going back and forth because I was trying to migrate to a 2.0 project and restore only worked on the command line.

**Comment by davkean** [comment]
@lifengl any ideas on what this could be? Basically we regist design-time global properties here: https://github.com/dotnet/roslyn-project-system/blob/b22cf2e196665e747a00c60d53aba0865567f329/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/CommandLineDesignTimeBuildPropertiesProvider.cs#L14. For some design-time builds these are not set to true, I have no idea how this is possible.

**Comment by davkean** [comment]
I debugged further into this, we're setting the "global properties" correctly from our stand point, and CPS is setting these as properties on the ProjectInstance before it schedules that off for a build.

**Comment by davkean** [comment]
Okay, got further here, a couple of things I noticed:

1. This only occurs when we believe we have "unsaved" changes, and hence serialize the ProjectInstance to MSBuild, instead of having MSBuild load the project file from disk. In this path, we don't set the "global" properties as actual global properties, but rather set them directly on the ProjectInstance. 

2. We believe we have unsaved changes because the NuGet.g.props have changed on disk - but we've not reloaded them. This is causing us to go down the serialize path. Given targets aren't current reloaded - we should avoid that. Also noticed that we're not comparing UTC file stamps which we should also fix.

Ultimately, I suspect we're serializing the ProjectInstance to MSBuild, and MSBuild thinks there's a newer version on disk and reloading it, which throws away our "global" properties. In the end, I suspect this is the cause: https://github.com/dotnet/roslyn-project-system/issues/1479.

**Comment by ChangePlaces** [comment]
I've hit this as well in one project in a solution. No idea what's causing it. It's preventing me from adding nuget packages

**Comment by srivatsn** [comment]
This looks to be a MSBuild issue https://devdiv.visualstudio.com/DevDiv/_workitems?id=385643&fullScreen=false&_a=edit @andygerlicher @cdmihai is there a GitHub bug tracking this?

**Comment by cdmihai** [comment]
Created https://github.com/Microsoft/msbuild/issues/1726 for investigation.

**Comment by hardhub** [comment]
Why it is closed if it is not fixed?

**Comment by davkean** [comment]
@hardhub This has been resolved as a duplicate against the MSBuild bug https://github.com/Microsoft/msbuild/issues/1726. This has been fixed in 15.3.

**Comment by hardhub** [comment]
@davkean thanks... awaiting 15.3

**Comment by AArnott** [comment]
This still repros on d15rel 26621.2. Is it really fixed?

**Comment by davkean** [comment]
@AArnott The first instance was fixed, we found another instance: https://github.com/Microsoft/msbuild/issues/2123, which is now a bug against CPS.

**Comment by AArnott** [comment]
Ah, I remember that one. Thanks.

**Comment by Janidbest** [comment]
I have happened to see this errors today on the class library .net standard project. Which was building fine with VS 2017 15.2 before, due to the update issue with 15.3.5 I have downgraded to 15.0 version. Now this is appearing on the solution. Sounds like I need to get to the bottom of the issue with 15.3.5 source control plugin to get this rid off.

**Comment by lifengl** [comment]
In 15.5, CPS will no longer batch build with different project instances.

Sent from my phone

On Sep 26, 2017, at 4:59 PM, Janardhan <notifications@github.com<mailto:notifications@github.com>> wrote:


I have happened to see this errors today on the class library .net standard project. Which was building fine with VS 2017 15.2 before, due to the update issue with 15.3.5 I have downgraded to 15.0 version. Now this is appearing on the solution. Sounds like I need to get to the bottom of the issue with 15.3.5 source control plugin to get this rid off.
