### ISSUE TITLE
Language Service is busted with 1.1 and restore

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#1666]
Repro Steps:
1. Create a new console app
2. Add NuGet package
3. Add code using the new types
4. Remove the NuGet package

Expected:
Errors in the error list.

Actual:
No errors, types are still highlighted, intellisense still provides removed package.

Notes:
I can't repro with with tfm ~~`netstandard1.0`~~ `netcoreapp1.0`, only with ~~`netstandard1.1`~~ `netcoreapp1.1`.

**Comment by mavasani** [comment]
@333fred I presume you meant netcoreapp1.0 and netcoreapp1.1 above, not netstandard. I am able to repro this and investigating further.

**Comment by 333fred** [comment]
Yes, updated the original post.

**Comment by mavasani** [comment]
We first register subscriptions for active configured project in our LS host during OnProjectFactoryCompletedAsync (https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs#L83), but the active project configuration is NoVariablesDefault, instead of Debug, AnyCPU. @Lifeng, is this expected?




After a few seconds, InitializeCoreAsync is invoked on LS Host (https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs#L104) and we try to make sure that we have subscriptions in place for active configured project here: https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/LanguageServiceHost.cs#L278.
At this point the active configured project has changed to one with configuration (Debug|AnyCPU), so we add new subscriptions for the new configured project.



From now on, we seem to be getting duplicate evaluations and design time build updates for both configured projects. Our mapping from project configuration to workspace project context didn't account for NoVariablesDefault case, and end up using the same underlying workspace context, causing duplicate references.

So, the primary question is: Is the active project configuration expected to be NoVariablesDefault at OnProjectFactoryCompletedAsync? If so, is it always going to be NoVariablesDefault when factory completes? If so, then we should stop registering subscriptions in this method, as we will eventually have the correct active configured project subsequently, and will register subscriptions for it. If it is not always guaranteed to be NoVariablesDefault at OnProjectFactoryCompletedAsync, then we can just add a check in OnProjectFactoryCompletedAsync to bail out if we have NoVariablesDefault active config.

**Comment by mavasani** [comment]
@srivatsn I believe we need to fix this for 15.1. Having duplicate metadata references at all the time can cause weird behavior similar to this repro.

**Comment by davkean** [comment]
I think we should fix this for 15.0.1.

**Comment by mavasani** [comment]
Followed up offline with @srivatsn and we are going to target this to master for now, and port it to any servicing branches if we see enough feedback.
