### ISSUE TITLE
Rebuilding a project causes a restore

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1747]
1. File -> New Console App (.NET Core)
2. Wait for restore
3. Rebuild

Expected: No restore
Actual: Project is restored

No idea why we're getting restored in this case. Saw this with: https://github.com/fsprojects/Paket/issues/2086

**Comment by davkean** [comment]
tag @natidea

**Comment by natidea** [comment]
This repro happens because NuGet has a solution restore feature that is checked. To uncheck it, Tools -> NuGet Package Manager -> Package Manager Settings -> "Automatically check for missing packages during build in Visual Studio". With this box unchecked, I don't see a restore step on build.

I suspect the restore is a NoOp since Project System is not nominating with any new information, but /cc @alpaix to confirm
