### ISSUE TITLE
Generate/Update .csproj using "dotnet restore" which uses project.json as an input

### ISSUE THREAD

**Issue by gulshan** [dotnet/roslyn-project-system#181]
How about keeping both project.json and .csproj, where .csproj is generated by the command `dotnet restore` and not synced in version control by default? The difference will be, instead of `dotnet restore` generating “project.lock.json” (and do other things), it will generate (or update) the “.csproj” file. Even both “project.lock.json” and “.csproj” can stay as both are being auto generated. Then a flag can be used in `dotnet restore` for generating .csproj. In the announcement, Microsoft is already saying- “CLI tool for doing any operations on the project file, for most scenario’s you would not edit the file”. IMHO, `dotnet restore` is most suited to be THAT CLI tool, which will take project.json as an input. The upsides will be-
 - Both formats of project.json and .csproj can stay unchanged. That means new generated .csproj will be compatible with earlier versions of Visual studio and other tools. `dotnet restore` even can insert explicit "include" list of project files in the .csproj file.
 - As .csproj is being auto generated and not in version control, developers do not have to deal with hand editing and merging .csproj.

**Comment by oaiey** [comment]
Filed a similar approach for the dotnet/cli#2992

**Comment by davkean** [comment]
Thanks for the issue. Appreciate the enthusiasm for project.json, however, [as previously announced](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/), we have no intentions to keeping it around in the future.

Based on this, I feel the community's efforts are better spent on providing feedback so that we can bring the great things from project.json to csproj.

We've got the following items already on our backlog, can you think of more?
https://github.com/dotnet/roslyn-project-system/issues/169
https://github.com/dotnet/roslyn-project-system/issues/107
https://github.com/dotnet/roslyn-project-system/issues/40
