### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by wjk** [dotnet/roslyn-project-system#246]
I noticed the documentation for the `RunPostBuildEvent` MSBuild property contains incorrect info; I suspect a typo [[link to affected file](https://github.com/dotnet/roslyn-project-system/blob/master/docs/well-known-project-properties.md)]. Specifically, I believe the `OnOutputUpdated` and `OnBuildSuccess` rows in the tables have their descriptions backwards. See below screenshot for how it appears at time of this writing.

![Documentation Typo](https://cloud.githubusercontent.com/assets/1915951/16163931/f7797da0-34a9-11e6-8acd-32270c452b84.png)

**Comment by davkean** [comment]
Good catch - I'd accept a contribution to fix if you like, otherwise I'll fix it next couple of days.

**Comment by paul1956** [comment]
@davkean I would like to contribute to VB but I have no idea how. Yes I know how to edit the code, and write tests. It is the :"contribution process" I don't understand. Is there a how to contribution, using VS2015 document for the complete novice? I have been using VB since it was released but am new to open source.

**Comment by davkean** [comment]
Which part of the contribution process? Git? How to submit a PR?

**Comment by paul1956** [comment]
Both, I was able to Clone Roslyn using Desktop GitHub on Windows 10 but I don't see how I get to a specific branch, do I need to clone that too? Then I fix the issue, which I have done and tested using the Zip version. But where do I go from there.

**Comment by wjk** [comment]
@paul1956 If you are using the command line, `git checkout -b my_branch` will create a new Git branch named “my_branch”. GitHub Desktop provides a "create branch" button (near the top of the window, located just to the right of the sidebar, next to the button identifying the branch (in your case, it probably says ”master”). Click that and it will open a popup containing a blank for the name and the branch to create it from. Fill in both, click Create Branch, and ta-da: you now have a brand new branch.

**Comment by paul1956** [comment]
OK I created a new branch "MyFix" from stabilization and I can open it in Explorer but not sure how I know it is "MyFix" I am working on. I did the fix (since it has been an issue since Master it doesn't matter to me what source I start with), then what?
![image](https://cloud.githubusercontent.com/assets/12789369/16167256/a9779e86-34a7-11e6-9060-4c67f31bcba5.png).

**Comment by paul1956** [comment]
I committed fix from Visual Studio but can't submit Pull Request.
![image](https://cloud.githubusercontent.com/assets/12789369/16167782/5cc29bf2-34ae-11e6-80e3-bebf5819c08d.png)

![image](https://cloud.githubusercontent.com/assets/12789369/16167780/3f6f1e54-34ae-11e6-8edf-b763cf39dadd.png)

**Comment by davkean** [comment]
You're trying to push to directly to the Roslyn's repo, instead of to your fork. You need to fork Roslyn, and push changes to it - from which you create PRs.

These are the steps you need to take:

1) Create a fork of a project (there's a Fork button on the front page of every repo) under your name
2) From the command-line type:
```git remote add origin https://github.com/paul1956/roslyn.git`
3) Then you want to push your branch to it; `git push origin`
4) Then create a new PR from the branch you pushed to the Roslyn repo.
