### ISSUE TITLE
Design-time builds warnings and error should show up in Error List

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#247]
Today any warnings/errors that occur during design-time builds are dropped on the floor - this makes it extremely difficult diagnose _why_ the language service fails to get populated - and why documents end up in the Miscellaneous Workspace. Customers are unaware of design-time builds - so unaware that targets run in a context outside of a full build,

We should push design-time builds & errors/warnings to the Error List making sure that we de-dup and favor ones from the build.

**Comment by davkean** [comment]
This is required for the P2P case to make sure the user sees warnings on bad references/projects.

**Comment by mavasani** [comment]
@basoundr Moving to you

**Comment by basoundr** [comment]
CPS has a DefaultErrorListProvider which listens to design time build errors and warnings and pushes them to errorlist. One of the reasons that we might not have seen any of the expected errors was because msbuild, while building, has a check to verify if the OutputPath is set with proper configuration. When this check fails, the rest of the design time build stops and hence no errors or warnings were reported. Hence I am closing this issue since we have the expected functionality in place already.

**Comment by davkean** [comment]
I looked at the code - it does not appear that design-time build errors and warnings are getting logged to the Error List.  The logger I see is only hooked up the Full Solution Builds and Single File Generators, I know that we sometimes see warnings/errors as if they did come from a design-time build, but I think we're getting confused - and it's getting logged by something else.

**Comment by davkean** [comment]
Also, I had failing design-time build and there were no errors.

**Comment by davkean** [comment]
I'm wrong, it looks like it *is* hooked up: http://index/?leftProject=Microsoft.VisualStudio.ProjectSystem.Implementation&leftSymbol=tzapwbdxydbe&file=Designers%5CProjectBuildSnapshotService.cs&line=203.

Okay, we the problem is that we're not always logging design-time build errors, trying to get a repro.

**Comment by srivatsn** [comment]
Can you open a separate bug for the cases where it's not showing up?
