### ISSUE TITLE
Edit and Continue Debugging not working on msbuildproj

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn-project-system#258]
##### Repro Steps:
- Create new msbuildproj console application using directions in [Getting Started](https://github.com/dotnet/roslyn-project-system/blob/master/docs/repo/Getting%20Started.md)
- Add some source code and start debugging
- Modify the source and reset the instruction pointer (CTRL+SHIFT+F10)
##### Expected

Debugging continues with modified source
##### Actual

Debugging continues with old source

**Comment by davkean** [comment]
This is a known missing feature, looks like we hadn't filed it. Thanks!

**Comment by tmat** [comment]
Should we make EnC work for Portable PDBs in RTM as well? Since Portable PDBs are the default I think we should, so that the user doesn't need to keep switching between Portable and Windows. Supporting EnC with Portable PDBs shouldn't be hard, a few days of work might suffice. FYI @ManishJayaswal

**Comment by srivatsn** [comment]
That would be good because then we can keep the default as portable pdb across all platforms. Currently there's some thinking about making full the default for projects created by VS in windows to get EnC to work. It would be unfortunate to introduce that oddity. When you say few days of work - what components need to change?

**Comment by tmat** [comment]
I believe it should only be Microsoft.DiaSymReader.PortablePdb: https://github.com/dotnet/roslyn/issues/1952
