### ISSUE TITLE
Issue warning for duplicate items (Compile, Reference, ProjectReference)

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn-project-system#311]
Should the new project system issue a warning when it detects duplicate items? It'd be nice to have a built-in diagnostic to detect this kind of situation and report to the user.

**Comment by davkean** [comment]
Hmm, I'm split on this. I do not want the project system to issue errors and warnings that MSBuild itself does not produce - otherwise, it leads to developers not trusting the Error List (because they build via the command-line or switch category -> Build) and these errors/warnings go away. Maybe a target that detects this?

**Comment by KirillOsenkov** [comment]
You're right, I should have filed this against MSBuild in the first place.

Filed https://github.com/Microsoft/msbuild/issues/804.
