### ISSUE TITLE
"Unrecognized Guid format" when Add Class

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#392]
1. Right-click on folder -> Add -> Add Class

![image](https://cloud.githubusercontent.com/assets/1103906/18023612/100b34b6-6bb0-11e6-90ba-f4733d688be9.png)

**Comment by 333fred** [comment]
#406 fixed the issue when opening an existing project. However, when creating a new project, it appears that the `ImplicitProjectPropertiesProvider` is getting created twice. The first time it's created, it's passed a GUID for the project. The second time it's created is when we call `projectProperties.ProjectGuid.GetValueAsync()`. This instance of the properties provider isn't the once that had the GUID set, and therefore the attempt to parse the GUID fails. @davkean, what's the expected lifecycle around the properties provider? If this is expected behavior, we'll have to work around it somehow.

**Comment by 333fred** [comment]
@lifengl, do you have any insight into this issue?

**Comment by davkean** [comment]
It's a configured project service, there's going to be 1 per configuration.
