### ISSUE TITLE
Certain check boxes in property pages have indeterminate state for new project

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#437]
1. Signing page:

![signingpage](https://cloud.githubusercontent.com/assets/10605811/18218066/38000202-7115-11e6-8856-618e2c58281a.png)
1. Application page:

![applicationpage](https://cloud.githubusercontent.com/assets/10605811/18218077/41a721c8-7115-11e6-85ad-f1cfe2e4831c.png)

**Comment by mavasani** [comment]
Also the below seems to be weird, no option is selected:

![treatwarningaserrors](https://cloud.githubusercontent.com/assets/10605811/18219003/3e1e8c5c-711b-11e6-92ad-c323b3a63904.png)

**Comment by davkean** [comment]
Yeah, I think these are lack of defaults in the props.

**Comment by mavasani** [comment]
@jinujoseph I thought you fixed this?

**Comment by RaulPerez1** [comment]
Some of this is the fallout of #813, going to revisit the list of things here after looking at that one.

**Comment by RaulPerez1** [comment]
@dotnet/project-system I need some input here - There are two approaches:

1) Add default properties for everything that's missing so that the cast that is forcing this to be indeterminate succeeds. One problem with this is that any new boolean property will always need to have a default value.

2) Adjust the check to check if the value is an empty string and if it is set the control state to false.

I'm more inclined to go for the second one which feels more robust and future proof. Also one of the values here (DelaySign) is explicitly set to an empty string by the targets if SignAssembly isn't set so there are valid cases where the property will be empty.

**Comment by davkean** [comment]
Defaults aren't always false, right?

**Comment by RaulPerez1** [comment]
Empty (which is the default for MsBuild) means false. IMO if you explicitly want to default to true at that point you should then add the default value.

**Comment by davkean** [comment]
Anyway you need to coordinate with the SDK to agree on who's defining defaults - looks to be a bunch of properties broken, including generate serialization assemblies, pdb, overflow/underflow, etc.

Just compare desktop with the .NET Core and you can see what's different/broken.

**Comment by srivatsn** [comment]
Wait we had discussed this a while and said that instead of adding defaults values in msbuild which may break existing projects, we should instead add defaults to the XAML rules and then create a rule provider like the existing UserFileWithXamlDefaults which gets the value from the project but if the value is not defined in the project, gets it from the XAML file instead. Just adding the defaults to the SDK will fix netcore but this will remain broken for desktop projects when we bring those up

**Comment by davkean** [comment]
Whoops didn't mean to close this...

**Comment by srivatsn** [comment]
The new provider would be something like ProjectFileWithXamlDefaults.

**Comment by RaulPerez1** [comment]
After some discussion and input from folks knowledgeable in CPS we decided to go with the defaults.
