### ISSUE TITLE
MSBuild build-only diagnostics disappear from error list when any change is made to project properties

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#445]
1. Create a .net core project
2. Restore NuGet packages
3. Build the project.
   This generates:
   `1>C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1825,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.`
4. Open error list to see MSB3276
5. Open property pages and change any property and save. The MSB3276 disappears from error list.

@heejaechang Tells me this is likely an issue with the MSBuild diagnostic provider, and may not be specific to net core projects.

**Comment by davkean** [comment]
"MSBUild diagnostic provider" - which component is that?

**Comment by mavasani** [comment]
@heejaechang - can you add more details? I am also not clear about this..

**Comment by heejaechang** [comment]
I don't know who is providing msbuild errors to error list. but I do know it is NOT us.

by looking at the symptom, it looks like whoever providing msbuild errors to error list seems not following contract of error list.

new error list, the error provider owns the data, so error list can ask them back when error list need data rather than error list keep every errors reported in memory.

the symptom looks like when error list ask back the provider data again, they already forgot out it and return nothing causing error list to remove those error from the error list.

**Comment by srivatsn** [comment]
CPS own the tabledatasource - this could be a CPS issue.

**Comment by basoundr** [comment]
The last I looked at the CPS code, they were handling to persist the warnings/errors.

@mavasani Could you please repro this issue to see if this is still an issue. If not, please close this issue.

**Comment by mavasani** [comment]
@basoundr I am unable to repro it on d15rc
