### ISSUE TITLE
Remove DefaultCapabilitiesProvider

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#559]
Once we move to new CPS bits which allows registering capabilities with project registration factory, we should add `ProjectCapabilities.ProjectConfigurationsInferredFromUsage` through that attribute and remove ProjectConfigurationsInferredFromUsageCapabilitiesProvider

**Comment by mavasani** [comment]
Additionally, we should also make sure that TargetFrameworkProjectConfigurationDimensionProvider is enabled via a new capability (instead of being tied to ProjectCapabilities.ProjectConfigurationsInferredFromUsage) that is also added from our project factory registration

**Comment by davkean** [comment]
We can remove CSharp/LanguageService capabilities from this class when CPS fixes #274485

**Comment by lifengl** [comment]
#274485 has been closed as "Won't fix".  Because dataflow doesn't consistently passes ExecutionContext, there is no easy way to address this issue other than a dataflow which imports anything based on capabilities must chain capabilities as its input dataflow.

The workaround today will add a capability provider to be loaded into all project types.  If you plan to keep it there, please add SupportsFileExtensionAttribute, so it is only loaded for .csproj/.vbproj files.
