### ISSUE TITLE
P2P refs aren't working for netcore projects

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#692]
P2P refs seems to have regressed.

Create a console app
create a class lib

reference the class lib from the console app and try using a type from it. Doesn't show up in intellisense.

A build works fine and after that it treats it as a metadata ref. Looks like the P2P hookup is not happening. Wonder if this is a roslyn issue but filing it here for first investigation.

**Comment by mavasani** [comment]
There are bunch of issues here, but it is primarily failing due to the fact that all the evaluations are actually failing with the following in the debug pane of output window when a project is newly created and auto-restore happens:

```
Target "_CheckForInvalidConfigurationAndPlatform" in file "C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets" from project "c:\users\mavasani\documents\visual studio 2017\Projects\ConsoleApp32\ConsoleApp32\ConsoleApp32.csproj" (target "DockerSetDevelopmentMode" depends on it):
The OutputPath property is not set for project 'ConsoleApp32.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='AnyCPU'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.
Done building target "_CheckForInvalidConfigurationAndPlatform" in project "ConsoleApp32.csproj" -- FAILED.
Done building project "ConsoleApp32.csproj" -- FAILED.
```

Even though they are failing, it seems CPS still calls back the evaluations which have seemingly random and non-deterministic values:

1. The `ProjectConfiguration` is sometimes Debug|AnyCPU and at times it is NoVariablesDefault
2. The TargetPath sometimes correctly gets reported as `bin\debug\<TF>\ClassLib.dll`, and then intellisense works. However, for most times TargetPath gets reported as `bin\debug\ClassLib.exe` or `ClassLib.exe` and we end up *not* adding a P2P ref as the design time build correctly has a `/reference:bin\debug\<TF>\ClassLib.dll`, and there is no existing project with this output path.
3. The extension for the TargetPath is always random, sometimes it is exe and sometimes it is dll - this is true for both Console Apps and ClassLibs - i.e. I have seen ConsoleApp.dll (netcoreapp) and ClassLib.exe (netstandard lib) being reported by evaluations.

Also note:

1. Design time builds never seem to be broken - i.e. they are always generated with correct ProjectConfiguration and have correct reference.
2. If I close and reopen restored solution, evaluations are never broken - the output window has no evaluation failed reports and none of the above symptoms seem to repro.

**Comment by mavasani** [comment]
@srivatsn This doesn't seem to be an issue with LanguageService or stale evaluations - I think the core issue here is the same that @nguerrera was mentioning at standup today.

**Comment by mavasani** [comment]
This should be fixed when we address https://github.com/dotnet/sdk/issues/203

**Comment by nguerrera** [comment]
I'm not sure it is the same issue. All my current changes are for after restore has happened, where things only break if you make new configurations or platforms.

The fix for _CheckForInvalidConfigurationAndPlatform before restore was made in msbuild: https://github.com/microsoft/msbuild/pull/1280

I believe this was inserted to VS, so it is surprising to see this error here.

**Comment by srivatsn** [comment]
@mavasani were you trying with the latest VS builds. I think an MSBuild with the fix for that issue was inserted last week.

**Comment by mavasani** [comment]
Yes, I am on d15rel 25831.00

**Comment by srivatsn** [comment]
Fixed now.
