### ISSUE TITLE
LaunchSettingsProvider.UpdateProfilesAsync should have string.IsNullOrEmpty check for activeProfile

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/roslyn-project-system#739]
Since in one of the code paths we try to get activeProfile from project properties and it always returns "" (empty string), but not null, if property is not set.

**Comment by abpiskunov** [comment]
@BillHiebert  fyi

**Comment by BillHiebert** [comment]
This is by design. Normally that function is called with null, to force it to re get the value of the active profile property. When it is called by a change to properties, and the property isn't defined. it will pass the empty string.. In this case, we know the property is not defined so there is no point trying to get it again.
