### ISSUE TITLE
Build tab error in project properties after 'dotnet migrate' a project

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn-project-system#745]
**Version Used**: 
VS 2017 RC public.d15rel/15.0.25909.2

**Steps to Reproduce**:

1. Clone the repro https://github.com/serilog/serilog-sinks-logentries.git
2. Open the solution serilog-sinks-logentries.sln in VS 2017
3. Click OK to migrate. The log says `Serilog.Sinks.Logentries` project is migrated,  the test project failed but it's not related to this issue.
4. Check the **Build** tab in project property pages

**Expected Behavior**:
Normal Build page

**Actual Behavior**:
![image](https://cloud.githubusercontent.com/assets/7583839/20276245/53d6f14c-aa50-11e6-8ca4-bf71ffd52d4d.png)

**Comment by jeremymeng** [comment]
Moved from https://github.com/dotnet/roslyn/issues/15215.

**Comment by srivatsn** [comment]
This is in the pre-restore state. This will get fixed once https://github.com/dotnet/sdk/issues/415 is fixed.

**Comment by john-t-white** [comment]
I know this issue is closed and the link says it is fixed, but I am running into the same issue.  My visual studio 2017 version is VisualStudio/public.d15rel/15.0.26014.0.  I am also getting an error that the OutputPath is missing when I build and noticed there is no default namespace set in the project properties.

**Comment by davkean** [comment]
@john-t-white Please open a new bug with a repro project.
