### ISSUE TITLE
ArgumentException at Line 104 ProjectLockFileWatcher.cs when creating a new .Net Core Console Project

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn-project-system#921]
On VS D15Prerel 26012.0

`objDirectory = _projectServices.Project.MakeRooted(objDirectory);` throws ArgumentException. 

Because  `objDirectory` is empty from the previous statement 
`var objDirectory = (string) await configurationGeneral.BaseIntermediateOutputPath.GetValueAsync().ConfigureAwait(false);`

Stack Trace
------------

   at Microsoft.Requires.NotNullOrEmpty(String value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.PathHelper.MakeRooted(UnconfiguredProject unconfiguredProject, String path)
   at Microsoft.VisualStudio.ProjectSystem.VS.ProjectLockFileWatcher.<GetProjectLockFilePathAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.VS.ProjectLockFileWatcher.<ProjectTree_ChangedAsync>d__11.MoveNext()

**Comment by basoundr** [comment]
Seems like the none of the XAML rule property is working and I don't see any CPS error in the output during the project load

**Comment by davkean** [comment]
When we fix the rules, we should make this not crash if its empty.

**Comment by davkean** [comment]
@srivatsn Can you get someone to have a look at this tomorrow morning - sounds like the builds are broken.

**Comment by RaulPerez1** [comment]
This may be a race condition on restoring. That property is coming from the SDK (common.props)

<BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)' == ''">$([System.IO.Path]::GetFullPath('$(RepositoryRootDirectory)bin\obj\$(MSBuildProjectName)'))\</BaseIntermediateOutputPath>

And opening an existing project (which already restored at least once) does not repro the issue.

**Comment by srivatsn** [comment]
But in the new SDK attribute, the props are always present and there is no restore needed at all.

**Comment by RaulPerez1** [comment]
Looks like the SDK attribute is what's causing the problem. Older projects didn't have it so that's why those are working fine. 

@srivatsn Who has more context on the SDK change? On the surface it looks like we may be missing matching MsBuild support and that's what's causing the missing imports. This is the build output of a manually modified project (hand created from the shipping template):

"E:\My Documents\Visual Studio 2017\Projects\ConsoleApp16\ConsoleApp16\Broken.csproj" (default target) (1) ->
  E:\My Documents\Visual Studio 2017\Projects\ConsoleApp16\ConsoleApp16\Broken.csproj : error MSB4040: There is no target in the project.

**Comment by davkean** [comment]
I installed today's build and it's working. 

Do you have this directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks?

**Comment by RaulPerez1** [comment]
Yes: 
![clipboard01](https://cloud.githubusercontent.com/assets/19919028/21165897/03c0d5d8-c157-11e6-85a3-2f8345d2de10.jpg)

I'm going to update my build to today's. If this is already fixed there's no sense in trying to drill down further. As a follow up, for preventing the crash in general - It looked like a whack a mole since the project is unusable without it's imports so there were many more errors after patching this one. Ideally we would block the project load on cases like this.

**Comment by RaulPerez1** [comment]
This is fixed on later builds, opened a new bug to handle missing targets gracefully.
