### ISSUE TITLE
Compile link include in external msbuild file not displayed in Solution explorer, VS2017

### ISSUE THREAD

**Issue by Antaris** [dotnet/roslyn-project-system#948]
I have a project defined in my `\src\Fx.Common\Fx.Common.csproj` path:

```xml
<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\..\SharedProperties.props" />
  <PropertyGroup Label="Configuration">
    <RootNamespace>Fx</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
    <Description>Common and utility services used for all V4-powered applications and libraries</Description>
    <Copyright>Fresh Egg Limited</Copyright>
    <AssemblyTitle>FX: Common Services</AssemblyTitle>
    <TargetFramework>netstandard1.6</TargetFramework>
    <AssemblyName>Fx.Common</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NETStandard.Library" Version="1.6.1" />
  </ItemGroup>
</Project>
```

In the root of my solution, alongside the solution folder, I have `\SharedVersionInfo.cs` which is generated as part of a Cake build for CI. Additionally, I've defined a `\SharedProperties.props` file at the root:

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)SharedVersionInfo.cs">
      <Link>Properties\SharedVersionInfo.cs</Link>
    </Compile>
  </ItemGroup>
</Project>
```

This is referenced by my project `Fx.Common`, but the `Link` element at `Properties\SharedVersionInfo.cs` is not displayed in Solution Explorer. I've tried without `Link` and it still does not display in Solution Explorer.

The project builds just fine though and carries the expected version information in its metadata.

**Comment by davkean** [comment]
cc @jviau

**Comment by jviau** [comment]
With the new `Sdk` attribute on the project node any `<Import />` within the project is ignored. @Antaris if you were to run `msbuild /pp:pp.txt` on Fx.Common.csproj you would not even see your import anywhere in that output file.

@cdmihai is this a known issue?

**Comment by cdmihai** [comment]
The SDK attribute does not cause other existing imports to be ignored, it just adds top and bottom implicit imports.

**Comment by jviau** [comment]
@cdmihai @Antaris nevermind, it wasn't showing because my import was reverted.

I am seeing the file being imported just fine
![linkedfile](https://cloud.githubusercontent.com/assets/5439812/21202740/7611e1a6-c204-11e6-8e9b-3ae81d49f611.png)

My Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Shared.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" />
  </ItemGroup>
</Project>
```

Shared.props is the same as the `\SharedProperties.props` above.

**Comment by dasMulli** [comment]
I played around with this a little after a short slack chat with @Antaris and discovered why it may seem to not work at first:
Every time I change the shared props file, the changes do not take effect no matter how much I edit the csproj or even if i unload and reload the project. Only a close/open solution makes those changes take effect (e.g. changing the value inside the Link-metadata).

**Comment by davkean** [comment]
Ah, yeah, that's currently a limitation in MSBuild. 

@cdmihai Do you already have a issue tracking this? Unsure if this should be a CPS - or MSBuild feature.

**Comment by cdmihai** [comment]
Which limitation is that? There's many limitations :)

**Comment by davkean** [comment]
That once an import has been loaded into a ProjectCollection its never reloaded.

**Comment by cdmihai** [comment]
Is this it? https://github.com/Microsoft/msbuild/issues/1185

A new ProjectCollection API to invalidate a specific entry would fix this right? Or something like `new Project(invalidateCache: true)`

**Comment by cdmihai** [comment]
Looks like we could pipe this constructor call all the way up to some public API: https://github.com/Microsoft/msbuild/blob/68b96728bc2b7c554a37d12723e68e5d37768743/src/XMakeBuildEngine/Evaluation/ProjectRootElementCache.cs#L131

**Comment by dasMulli** [comment]
There also is #268 that seems related..
Would be great if changes could be detected to the imported file just like to the csproj..

**Comment by davkean** [comment]
@dasMulli Thanks.

I'm going to close this as you've resolved "why" they weren't showing up. We'll use #268 to track reloading props/targets.

**Comment by cristobalito** [comment]
I'm seeing a similar issue to this - with very similar code to @jviau, I don't see the sharedassemblyinfo.cs under in Visual Studio (15.3.5).

**Comment by kg** [comment]
I'm also hitting this in visual studio both 2015 and 2017, ItemGroups in .props/.targets files don't seem to show up in solution explorer. Project references do, however, unless you hide them in a ```<Choose>``` (which iirc is the recommended solution for VS 'punching through' into conditional itemgroups).

For example my .props contains:
```xml
  <ItemGroup Condition=" '$(ShaderDirectory)' != '' ">
    <ShaderText Include="$(ShaderDirectory)\*.fx" />
    <None Include="$(ShaderDirectory)\*.fxh" />
```
Compiles work correctly but for the items to show up in the solution explorer I have to copy the None directly into the csproj. Is there some property I can set to avoid needing to duplicate the itemgroup? Is it because it uses Condition?

**Comment by davkean** [comment]
@kg This is just how the legacy project system has behaved since 2005, it's only ever showed items that are listed in the project itself. It also doesn't handle "globs" very well, and will expand them every chance it has. We won't be making changes in this area.

The new project-system does support items coming from props/targets and supports globs. However, it won't show items from outside of the project code, unless they are marked with the Link metadata.
